repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v1.2.0
    hooks:
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E309,E501
    -   id: check-json
    -   id: check-yaml
    -   id: fix-encoding-pragma
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: name-tests-test
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
        files: requirements-dev.txt
-   repo: git://github.com/asottile/reorder_python_imports
    sha: v1.0.1
    hooks:
    -   id: reorder-python-imports
