language: python

matrix:
  include:
  - env: TOXENV=py35
    python: "3.5"
  - env: TOXENV=py36
    python: "3.6"
  - env: TOXENV=pre-commit
    python: "3.6"
  - env: TOXENV=cover
    python: "3.6"
  - env: TOXENV=docs
  - env: TOXENV=flake8
    python: "3.6"

install:
- "pip install tox coveralls"
script:
- tox -e $TOXENV
after_success:
- coveralls
# Faster runs on container based infrastucture
sudo: false
